import { MDNGroup, MDNGroupCSSModules } from "./types";

export const defaultGroupsOrder: MDNGroup[] = [
	'Compositing and Blending',
	'CSS Animations',
	'CSS Backgrounds and Borders',
	'CSS Basic User Interface',
	'CSS Box Alignment',
	'CSS Box Model',
	'CSS Color',
	'CSS Columns',
	'CSS Containment',
	'CSS Counter Styles',
	'CSS Display',
	'CSS Flexible Box Layout',
	'CSS Fonts',
	'CSS Fragmentation',
	'CSS Generated Content',
	'CSS Grid Layout',
	'CSS Images',
	'CSS Inline',
	'CSS Lists and Counters',
	'CSS Logical Properties',
	'CSS Masking',
	'CSS Miscellaneous',
	'CSS Motion Path',
	'CSS Overflow',
	'CSS Pages',
	'CSS Positioning',
	'CSS Ruby',
	'CSS Scroll Anchoring',
	'CSS Scroll Snap',
	'CSS Scrollbars',
	'CSS Shapes',
	'CSS Speech',
	'CSS Table',
	'CSS Text Decoration',
	'CSS Text',
	'CSS Transforms',
	'CSS Transitions',
	'CSS Variables',
	'CSS Will Change',
	'CSS Writing Modes',
	'CSSOM View',
	'Filter Effects',
	'MathML',
	'Microsoft Extensions',
	'Mozilla Extensions',
	'Pointer Events',
	'WebKit Extensions'
]

export const defaultGroupsOrderCSSModules: MDNGroupCSSModules[] = ['Composes', ...defaultGroupsOrder]
